// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HastaAkshar",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "HastaAkshar",
            targets: ["AppModule"],
            bundleIdentifier: "dnyaneshwari.gogawale.HastaAkshar",
            teamIdentifier: "474MDX8R3T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "HastaAkshar uses the front camera to detect your hand pose in real time and provide feedback on your mudra.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)